---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Hacking Cluster IAM Resources.'

Resources:

  BastionHostRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: BastionHostEKSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow EKS operations
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                  - eks:ListClusters
                  - eks:AccessKubernetesApi
                Resource: "*"
              
              # Allow access to ECR
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

              # Allow access to SSM for session management
              - Effect: Allow
                Action:
                  - ssm:DescribeSession
                  - ssm:GetSession
                  - ssm:StartSession
                  - ssm:TerminateSession
                  - ssm:DescribeInstanceInformation
                Resource: "*"

              # Allow reading Kubernetes configuration files in S3
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: "*"

  BastionHostInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref BastionHostRole

Outputs:
  InstanceProfileArn:
    Description: Name of the Bastion Host Instance Profile
    Value: !Ref BastionHostInstanceProfile
    Export:
      Name: BastionHostInstanceProfile
