---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Hacking Cluster IAM Resources.'

Resources:

  EKSHackingClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: EKSHackingClusterRole
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False 
      - Key: CanDelete
        Value: True
  
  EKSHackingNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      RoleName: EKSHackingNodeRole
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False
      - Key: CanDelete
        Value: True

Outputs:
  EKSHackingClusterRole:
    Description: "The EKS Hacking Cluster role"
    Value: !GetAtt  EKSHackingClusterRole.Arn
    Export:
      Name: EKSHackingClusterRoleARN

  EKSHackingNodeRole:
    Description: "The EKS Hacking Node role"
    Value: !GetAtt EKSHackingNodeRole.Arn
    Export:
      Name: EKSHackingNodeRoleARN
