apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-web-app-deployment
  namespace: vulnerable-web-app
  labels:
    app: vulnerable-web-app-webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-web-app-webgoat
  template:
    metadata:
      labels:
        app: vulnerable-web-app-webgoat
    spec:
      containers:
      - name: vulnerable-web-app
        image: webgoat/webgoat
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent