apiVersion: v1
kind: Service
metadata:
  name: vulnerable-web-app-service
  namespace: vulnerable-web-app
  labels:
    app: vulnerable-web-app-webgoat
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-arn: {{TARGET_GROUP_ARN}}
    service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules: "true"
spec:
  type: LoadBalancer
  selector:
    app: vulnerable-web-app-webgoat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080