apiVersion: v1
kind: Service
metadata:
  name: ${KUBE_NAMESPACE}-${APPLICATION_NAME}-service
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${KUBE_NAMESPACE}-${APPLICATION_NAME}
spec:
  type: ClusterIP
  selector:
    app: ${KUBE_NAMESPACE}-${APPLICATION_NAME}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080