apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${KUBE_NAMESPACE}-deployment
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${KUBE_NAMESPACE}-webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${KUBE_NAMESPACE}-webgoat
  template:
    metadata:
      labels:
        app: ${KUBE_NAMESPACE}-webgoat
    spec:
      #serviceAccountName: aws-load-balancer-controller
      containers:
      - name: ${KUBE_NAMESPACE}
        image: webgoat/webgoat
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent