apiVersion: v1
kind: Service
metadata:
  name: ${KUBE_NAMESPACE}-service
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${KUBE_NAMESPACE}-webgoat
spec:
  type: ClusterIP
  selector:
    app: ${KUBE_NAMESPACE}-webgoat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080