---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bastion Host IAM Resources.'

Resources:

  BastionHostRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: BastionHostEKSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow EC2 operations
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: "*"
              
              # Allow EKS operations
              - Effect: Allow
                Action:
                  - eks:*
                Resource: "*"
              
              # Allow access to ECR
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

              # Allow access to SSM for session management
              - Effect: Allow
                Action:
#                  - ssm:DescribeSession
#                  - ssm:GetSession
                  - ssm:StartSession
                  - ssm:TerminateSession
                  - ssm:DescribeInstanceInformation
                Resource: "*"

              # Allow reading Kubernetes configuration files in S3
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: "*"

              # Allow access to IAM OIDC Identity Providers
              - Effect: "Allow"
                Action:
                  - iam:GetOpenIDConnectProvider
                  - iam:CreateRole
                  - iam:GetRole
                  - iam:TagRole
                  - iam:AttachRolePolicy
                  - iam:CreateOpenIDConnectProvider
                  - iam:AddClientIDToOpenIDConnectProvider
                  - iam:RemoveClientIDFromOpenIDConnectProvider
                  - iam:PassRole
                  - iam:UpdateRole
                  - iam:UpdateRoleDescription
                  - iam:ListPolicies
                  - iam:CreatePolicy
                  - iam:CreatePolicyVersion
                  - iam:UpdateAssumeRolePolicy
                  - iam:PutRolePolicy
                  - iam:TagPolicy
                  - iam:TagOpenIDConnectProvider
                  - iam:ListAttachedRolePolicies
                Resource: "*"

              # Allow access to CloudFormation Stacks
              - Effect: "Allow"
                Action:
                  - cloudformation:*
                Resource: "*"

  BastionHostInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref BastionHostRole

Outputs:
  BastionHostRoleArn:
    Description: ARN of the Bastion Host Role
    Value: !GetAtt BastionHostRole.Arn
    Export:
      Name: BastionHostRoleArn

  InstanceProfileArn:
    Description: Name of the Bastion Host Instance Profile
    Value: !Ref BastionHostInstanceProfile
    Export:
      Name: BastionHostInstanceProfile
