---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates the EKS Infrastructure - Cluster and Nodegroup.'

Parameters:
  ClusterName:
    Type: String
    Default: $CLUSTER_NAME
    Description: Name of the EKS Cluster
  NodeGroupName:
    Type: String
    Default: EKSPublicClusterNodeGroup
    Description: Name of the EKS NodeGroup
  AmiId:
    Type: String
    Default: $AMI_ID
    Description: AMI ID used for Nodes
  DesiredCapacity:
    Type: Number
    Default: 1
    Description: Desired number of worker nodes
  MaxSize:
    Type: Number
    Default: 2
    Description: Max number of worker nodes
  MinSize:
    Type: Number
    Default: 1
    Description: Min number of worker nodes

Resources:
  EKSPublicCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      AccessConfig:
        AuthenticationMode: API_AND_CONFIG_MAP
        BootstrapClusterCreatorAdminPermissions: true
      ResourcesVpcConfig:
        EndpointPrivateAccess: true
        EndpointPublicAccess: true 
        SubnetIds:
          - !ImportValue EKSPublicCluster-PublicSubnetOne
          - !ImportValue EKSPublicCluster-PublicSubnetTwo
          - !ImportValue EKSPublicCluster-PrivateSubnetOne
          - !ImportValue EKSPublicCluster-PrivateSubnetTwo
        SecurityGroupIds:
          - !ImportValue EKSPublicCluster-ControlPlaneSecurityGroup
          - !ImportValue EKSPublicCluster-WorkerNodeSecurityGroup
      RoleArn: !ImportValue EKSClusterRoleARN
      Tags:
      - Key: Deployment
        Value: IaC 
      - Key: CostMoney
        Value: True
      - Key: CanDelete
        Value: True

  EKSPublicClusterNodeGroup:
    DependsOn:
      - EKSPublicCluster
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref ClusterName
      InstanceTypes: 
        - t3.large # This can't be a t2.micro. If you see a can't assign IP Error for pods, the instance is too small
      NodegroupName: !Ref NodeGroupName
      NodeRole: !ImportValue EKSClusterNodeRoleARN
      ScalingConfig:
        DesiredSize:  !Ref DesiredCapacity
        MaxSize:  !Ref MaxSize
        MinSize:  !Ref MinSize
      Subnets: 
          - !ImportValue EKSPublicCluster-PublicSubnetOne
          - !ImportValue EKSPublicCluster-PublicSubnetTwo
          - !ImportValue EKSPublicCluster-PrivateSubnetOne
          - !ImportValue EKSPublicCluster-PrivateSubnetTwo
      LaunchTemplate:
        Id: !Ref EKSPublicClusterLaunchTemplate
  
  EKSPublicClusterLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EKSPublicClusterLaunchTemplate
      VersionDescription: "Bootstrap the Node, and Install the Cloud Agent."
      LaunchTemplateData:
        ImageId: !Ref AmiId
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 20
        #Manually add in SGs after creation
        SecurityGroupIds:
          - !ImportValue EKSPublicCluster-ControlPlaneSecurityGroup
          - !ImportValue EKSPublicCluster-WorkerNodeSecurityGroup
        #KeyName: !ImportValue EKSKeyPair  # Need to create, only used for troubleshooting
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe

            # Bootstrap the Node - Register it to the EKS Cluster
            set -ex
            B64_CLUSTER_CA=$(aws eks describe-cluster --name ${ClusterName} --region us-east-1 --query cluster.certificateAuthority.data)
            B64_CLUSTER_CA=$(echo $B64_CLUSTER_CA | sed 's/"//g')
            API_SERVER_URL=$(aws eks describe-cluster --name ${ClusterName} --region us-east-1 --query cluster.endpoint)
            K8S_CLUSTER_DNS_IP=10.100.0.10

            /etc/eks/bootstrap.sh ${ClusterName} --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=i${AmiId},eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=${NodeGroupName} --max-pods=17' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP --use-max-pods false

Outputs:
  ClusterName:
    Value: !Ref ClusterName
    Description: This is the ClusterName
    Export:
      Name: ClusterName