---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Public Cluster IAM Resources.'

Resources:

  EKSPublicCluster-Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: EKSPublicCluster-Role
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False 
      - Key: CanDelete
        Value: True
  
  EKSPublicCluster-NodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      RoleName: EKSPublicCluster-NodeRole
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False
      - Key: CanDelete
        Value: True

Outputs:
  EKSPublicCluster-Role:
    Description: "The EKS Publice Cluster IAM Role"
    Value: !GetAtt  EKSPublicCluster-Role.Arn
    Export:
      Name: EKSPublicCluster-RoleARN

  EKSPublicCluster-NodeRole:
    Description: "The EKS Public Cluster Node IAM Role"
    Value: !GetAtt EKSPublicCluster-NodeRole.Arn
    Export:
      Name: EKSPublicCluster-NodeRoleARN
