---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Cluster IAM Resources.'

Resources:

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: EKSClusterRole
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False 
      - Key: CanDelete
        Value: True
  
  EKSClusterNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      RoleName: EKSClusterNodeRole
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False
      - Key: CanDelete
        Value: True

Outputs:
  EKSClusterRole:
    Description: "The EKS Cluster IAM Role"
    Value: !GetAtt  EKSClusterRole.Arn
    Export:
      Name: EKSClusterRoleARN

  EKSClusterNodeRole:
    Description: "The EKS Cluster Node IAM Role"
    Value: !GetAtt EKSClusterNodeRole.Arn
    Export:
      Name: EKSClusterNodeRoleARN
