---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a VPC Peering connection between two VPCs.

Resources:

  # Who Requests/Accepts the VPC Peering Connection
  EKSVPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue BHVpcId
      PeerVpcId: !ImportValue EKSPublicCluster-VpcId
      PeerRegion: us-east-1 # Region of Peer VPC
      Tags:
        - Key: Name
          Value: EKSPublicCluster-VpcPeering
        - Key: Deployment
          Value: IaC
        - Key: CostMoney
          Value: false
        - Key: CanDelete
          Value: false

  RouteToEKSVPC:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue EKSPublicCluster-VpcPublicRouteTable
      DestinationCidrBlock: !ImportValue BHVpcCidrBlock
      VpcPeeringConnectionId: !Ref EKSVPCPeeringConnection

  RouteToBHVPC:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue BHVpcPublicRouteTable
      DestinationCidrBlock: !ImportValue EKSPublicCluster-VpcCidrBlock
      VpcPeeringConnectionId: !Ref EKSVPCPeeringConnection

