---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Public Cluster IAM Resources.'

Resources:

  EKSPublicClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: EKSPublicClusterRole
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False 
      - Key: CanDelete
        Value: True
  
  EKSPublicClusterNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      RoleName: EKSPublicClusterNodeRole
      Tags: 
      - Key: Deployment
        Value: IaC
      - Key: CostMoney
        Value: False
      - Key: CanDelete
        Value: True

Outputs:
  EKSPublicClusterRole:
    Description: "The EKS Publice Cluster IAM Role"
    Value: !GetAtt  EKSPublicClusterRole.Arn
    Export:
      Name: EKSPublicClusterRoleARN

  EKSPublicClusterNodeRole:
    Description: "The EKS Public Cluster Node IAM Role"
    Value: !GetAtt EKSPublicClusterNodeRole.Arn
    Export:
      Name: EKSPublicClusterNodeRoleARN
