Resources:

    AWSLoadBalancerControllerRepository:
        Type: AWS::ECR::Repository
        Properties:
            EmptyOnDelete: false
            ImageScanningConfiguration:
                ScanOnPush: true
            RepositoryName: eks/aws-load-balancer-controller
            RepositoryPolicyText:
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Sid": "AllowPushPull",
                            "Effect": "Allow",
                            "Principal": {
                                "AWS": [
                                    !Sub "arn:aws:iam::${AWS::AccountId}:root",
                                ]
                            },
                            "Action": [
                                "ecr:BatchGetImage",
                                "ecr:BatchCheckLayerAvailability",
                                "ecr:CompleteLayerUpload",
                                "ecr:GetDownloadUrlForLayer",
                                "ecr:InitiateLayerUpload",
                                "ecr:PutImage",
                                "ecr:UploadLayerPart"
                            ]
                        }
                    ]
                }